name: Build

on:
  push:
    branches:
      - main
      - release
      - pre-release
    paths:
      - '.github/**'
      - 'deps/**'
      - 'src/**'
      - '.gitignore'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]

env:
  build_dir: "build"
  config: "Release"
  artifact: "native"
  nt: "4"

jobs:

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: seanmiddleditch/gha-setup-ninja@master

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure CMake
        run: cmake . -G Ninja -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}

      - name: Build library sources
        run: cmake --build ${{ env.build_dir }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.artifact}}
          path: ${{env.build_dir}}/gpusandbox_win_x64.exe


  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure CMake
        run: cmake . -G Ninja -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
        env:
          CC: gcc-9
          CXX: g++-9

      - name: Build library sources
        run: cmake --build ${{ env.build_dir }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.artifact}}
          path: ${{env.build_dir}}/gpusandbox_linux_x64

  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure CMake x64
        run: cmake . -G Ninja -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCMAKE_OSX_ARCHITECTURES=x86_64

      - name: Build library sources x64
        run: cmake --build ${{ env.build_dir }}

      - name: Configure CMake arm64
        run: cmake . -G Ninja -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCMAKE_OSX_ARCHITECTURES=arm64
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Build library sources arm64
        run: cmake --build ${{ env.build_dir }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.artifact}}
          path: |
            ${{env.build_dir}}/gpusandbox_macos_x64
            ${{env.build_dir}}/gpusandbox_macos_arm64
